#!/bin/sh

changed=0
theme_added=0

if ! uci -q get "luci.themes.Freenetic" 2>/dev/null; then
	uci set "luci.themes.Freenetic=/luci-static/freenetic"
	changed=1
	theme_added=1
fi

if [ "$PKG_UPGRADE" != 1 ] && [ "$theme_added" = 1 ] &&
   [ "$(uci -q get luci.main.mediaurlbase 2>/dev/null)" != /luci-static/freenetic ]; then
	uci set "luci.main.mediaurlbase=/luci-static/freenetic"
	changed=1
fi

if [ $changed = 1 ]; then
	uci commit luci
fi

exit 0
