#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=90

PROG=/usr/bin/mihomo

start_service() {
	local enabled home config
	config_load mihomo
	config_get_bool enabled main enabled 0
	config_get home main home '/etc/mihomo'
	config_get config main config '/etc/mihomo/config.yaml'
	[ "$enabled" = 1 ] || return 0
	[ -x "$PROG" ] || {
		logger -t mihomo 'Mihomo binary is not installed'
		return 1
	}
	[ -f "$config" ] || {
		logger -t mihomo 'Mihomo configuration is missing'
		return 1
	}
	procd_open_instance
	procd_set_param command "$PROG" -d "$home" -f "$config"
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/mihomo "$config"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger mihomo network firewall
}
